### ISSUE TITLE
Error de ejecución

### ISSUE THREAD

**Issue by pabloriutort** [pabloriutort/EngendroBot#1]
Después de un fork-clone he hecho:
```
docker build . -t telegram-bot
```
Lo cual ha ido bien porque me ha creado la imagen, pero al ejecutarla me sale el siguiente error:
```
$ docker run telegram-bot
Traceback (most recent call last):
  File "/usr/local/engendro-bot/main.py", line 29, in <module>
    engendro = Engendro(os.environ['BOT_TOKEN'])
  File "/usr/lib/python3.5/os.py", line 725, in __getitem__
    raise KeyError(key) from None
KeyError: 'BOT_TOKEN'
```
Alguna idea @Nosk14?

**Comment by Nosk14** [comment]
El problema es que la variable de entorno BOT_TOKEN no está definida. Debes pasársela al ahcer el run:

`docker run --env BOT_TOKEN=<TOKEN> telegram-bot`

**Comment by pabloriutort** [comment]
Buena esa! Gracias :)

2017-01-17 12:31 GMT+01:00 Nosk14 <notifications@github.com>:
